In [281]:
import pandas as pd
import os
import numpy as np
from pprint import pprint

# ajustando algumas configurações para prints
pd.set_option('display.max_columns', None)        # todas as colunas
pd.set_option('display.max_rows', None)           # todas as linhas
pd.set_option('display.width', None)              # largura automática
pd.set_option('display.max_colwidth', None)       # conteúdo completo das células
pd.set_option('display.expand_frame_repr', False) # evita quebrar dataframe em várias linhas

In [282]:
# pegando a pasta de trabalho para poder extrair os dados do dataset
PASTA_TRABALHO = os.path.dirname(os.path.abspath(os.getcwd()))

## Lendo e armazenando todas as tabelas dos anos necessários

In [283]:
# lista com os nomes das pastas que contem os datasets
nomes_arquivos = ["2024", "2025", "2026"]

# dicionario que contêm todos os dataframes do respectivo ano no seguinte formato:
"""
    ano1:
        ocorrencia_ano1,
        acorrencia_pessoa_ano1,
        acorrencia_todas_causas_ano1
    ano2:
        ...
"""
dataframes_por_ano = {}

# percorre e salva todos as dataframes dos anos escolhidos
for ano in nomes_arquivos:
    diretorio_dataframe = os.path.join(PASTA_TRABALHO, "dataset", ano)

    # percorre todas as tabelas que existem nesse ano (só existe um arquivo)
    for tabela in os.listdir(diretorio_dataframe):

        caminho = os.path.join(diretorio_dataframe, tabela)
        data_frame = pd.read_csv(caminho, sep=";", encoding="latin1") # adiciona a tabela em questão ao dicionário temporário

    dataframes_por_ano[ano] = data_frame # adiciona a tabela de dados ao respectivo ano

## juntando as tabelas distintas dos 3 anos em somente uma tabela

In [284]:
dataset = pd.concat([df for df in dataframes_por_ano.values()])

## Alterando os tipos de dados para não ter nunhum tipo de conflito com as transformações e armazenar de forma correta os dados

In [ ]:
print(dataset["km"].map(type).value_counts())

# DATA
dataset["data_inversa"] = pd.to_datetime(
    dataset["data_inversa"],
    format="%Y-%m-%d"
)


# HORÁRIO
dataset["horario"] = pd.to_datetime(
    dataset["horario"],
    format="%H:%M:%S"
).dt.time


# VALORES NUMÉRICOS
# trocando a virgula por ponto para poder converter para float
dataset["latitude"] = pd.to_numeric(
    dataset["latitude"].astype(str).str.replace(",", "."),
    errors="coerce"
)

dataset["longitude"] = pd.to_numeric(
    dataset["longitude"].astype(str).str.replace(",", "."),
    errors="coerce"
)

# passando para o tipo numérico
dataset["latitude"] = pd.to_numeric(
    dataset["latitude"],
    errors="coerce"
)

dataset["longitude"] = pd.to_numeric(
    dataset["longitude"],
    errors="coerce"
)

dataset["km"] = pd.to_numeric(
    dataset["km"].astype(str).str.replace(",", "."),
    errors="coerce"
)

dataset["km"] = pd.to_numeric(
    dataset["km"],
    errors="coerce"
)

km
<class 'str'>    455060
Name: count, dtype: int64

km
0.0       2157
1.0       1929
2.0       1877
3.0       1823
5.0       1657
4.0       1646
7.0       1263
6.0       1209
19.0      1058
10.0      1037
16.0      1036
22.0      1031
17.0      1013
8.0       1008
12.0      1005
11.0       993
13.0       992
119.0      986
9.0        960
117.0      959
15.0       958
115.0      957
14.0       951
21.0       934
18.0       917
20.0       917
70.0       883
58.0       874
121.0      861
83.0       857
123.0      852
65.0       850
122.0      849
145.0      845
147.0      827
118.0      820
104.0      820
120.0      817
82.0       810
124.0      803
69.0       801
25.0       798
146.0      797
112.0      797
116.0      786
148.0      784
144.0      783
105.0      783
94.0       782
95.0       781
50.0       781
23.0       781
24.0       778
51.0       771
86.0       771
109.0      769
64.0       768
108.0      762
62.0       751
110.0      732
88.0       722
46.0       719
92.0       717
67.0       716
80.0       708
61.0       708
138.0      704
111.0      704
85.0       704
72.0       703
136.0      703
57.0       701
68.0       698
71.0       697
113.0      693
42.0       691
114.0      689
126.0      686
96.0       683
49.0       683
186.0      675
84.0       672
174.0      668
52.0       667
143.0      665
137.0      660
48.0       654
97.0       652
27.0       652
40.0       651
89.0       651
59.0       650
98.0       649
90.0       648
99.0       648
66.0       646
47.0       640
28.0       639
149.0      635
139.0      635
79.0       635
142.0      635
107.0      633
45.0       628
26.0       625
127.0      623
75.0       617
103.0      614
172.0      611
81.0       608
134.0      605
38.0       604
202.0      603
34.0       600
30.0       600
39.0       598
169.0      596
41.0       596
74.0       593
184.0      593
219.0      592
152.0      591
60.0       591
176.0      591
91.0       590
106.0      584
33.0       583
125.0      578
43.0       575
102.0      574
129.0      572
87.0       569
100.0      566
210.0      565
204.0      564
77.0       564
175.0      564
130.0      560
141.0      559
56.0       559
32.0       556
180.0      547
205.0      547
222.0      546
63.0       545
36.0       542
282.0      541
185.0      540
93.0       539
31.0       537
44.0       535
228.0      535
177.0      534
37.0       532
197.0      531
306.0      530
173.0      530
131.0      528
297.0      525
53.0       525
187.0      525
54.0       523
183.0      523
151.0      523
322.0      520
35.0       520
198.0      518
78.0       517
170.0      515
216.0      514
313.0      512
29.0       512
296.0      509
196.0      508
150.0      506
218.0      501
276.0      501
224.0      499
269.0      498
207.0      498
101.0      497
155.0      497
128.0      495
312.0      492
182.0      490
217.0      488
200.0      488
225.0      487
132.0      486
189.0      485
268.0      484
330.0      484
188.0      484
171.0      484
484.0      482
350.0      482
206.0      480
179.0      480
140.0      480
160.0      477
221.0      473
263.0      472
181.0      472
326.0      472
208.0      472
516.0      471
135.0      471
178.0      469
265.0      467
260.0      467
220.0      467
163.0      455
517.0      454
203.0      451
298.0      451
283.0      448
133.0      447
156.0      446
153.0      446
230.0      445
327.0      444
73.0       443
280.0      443
309.0      440
157.0      439
223.0      437
76.0       436
266.0      435
300.0      434
55.0       433
209.0      432
248.0      431
352.0      430
334.0      430
199.0      429
213.0      427
279.0      424
211.0      424
490.0      424
262.0      420
215.0      420
308.0      418
212.0      416
264.0      416
310.0      414
258.0      413
486.0      410
158.0      409
333.0      408
348.0      408
214.0      407
515.0      407
227.0      407
281.0      406
504.0      406
294.0      405
323.0      405
270.0      404
154.0      402
328.0      401
193.0      399
351.0      398
513.0      397
523.0      396
201.0      395
343.0      395
325.0      394
514.0      394
295.0      392
321.0      388
314.0      384
316.0      383
251.0      379
501.0      379
245.0      378
192.0      378
168.0      377
159.0      376
385.0      376
191.0      375
491.0      374
530.0      372
195.0      368
506.0      368
240.0      367
277.0      367
503.0      365
285.0      364
341.0      364
320.0      364
521.0      363
347.0      363
342.0      363
231.0      362
324.0      362
255.0      362
272.0      360
242.0      360
311.0      360
190.0      359
518.0      359
331.0      359
249.0      357
305.0      356
485.0      355
307.0      353
0.5        353
425.0      353
252.0      351
243.0      350
284.0      348
236.0      348
502.0      348
623.0      347
166.0      346
345.0      345
340.0      344
483.0      344
194.0      343
286.0      342
509.0      342
288.0      341
267.0      341
257.0      340
482.0      339
246.0      338
318.0      338
229.0      337
545.0      337
526.0      335
414.0      332
162.0      332
561.0      331
226.0      331
499.0      330
253.0      329
487.0      329
167.0      328
4.5        328
525.0      325
389.0      324
165.0      323
273.0      323
304.0      322
275.0      320
315.0      320
496.0      320
511.0      319
422.0      318
456.0      317
161.0      316
512.0      316
402.0      316
299.0      313
481.0      313
261.0      312
442.0      312
290.0      311
247.0      310
505.0      309
293.0      308
301.0      306
522.0      306
428.0      305
302.0      305
329.0      304
409.0      304
319.0      303
404.0      302
399.0      302
360.0      302
510.0      301
439.0      301
488.0      301
250.0      298
415.0      298
164.0      298
292.0      298
492.0      298
519.0      297
435.0      297
289.0      295
393.0      295
500.0      294
332.0      291
475.0      291
621.0      290
303.0      290
498.0      289
271.0      289
412.0      289
362.0      288
287.0      288
528.0      287
238.0      287
232.0      287
3.5        286
239.0      286
278.0      286
349.0      286
478.0      286
407.0      286
317.0      286
344.0      282
494.0      282
235.0      281
355.0      281
620.0      280
426.0      280
622.0      278
274.0      277
423.0      276
413.0      276
405.0      274
244.0      274
2.5        273
234.0      272
259.0      271
618.0      271
256.0      270
424.0      270
357.0      269
438.0      269
427.0      269
387.0      268
335.0      268
254.0      268
524.0      267
440.0      266
383.0      266
532.0      266
614.0      263
386.0      263
507.0      262
410.0      261
495.0      261
233.0      256
416.0      255
520.0      254
384.0      253
527.0      252
369.0      252
388.0      249
444.0      249
508.0      249
380.0      247
403.0      247
241.0      247
421.0      246
497.0      246
617.0      245
434.0      244
624.0      243
437.0      243
1.5        243
489.0      243
747.0      241
336.0      240
291.0      238
396.0      237
356.0      235
237.0      235
429.0      234
477.0      234
436.0      234
605.0      233
5.5        233
493.0      233
358.0      233
365.0      232
546.0      232
395.0      231
361.0      231
597.0      231
346.0      226
615.0      225
339.0      225
446.0      224
378.0      223
401.0      223
418.0      222
625.0      222
397.0      222
535.0      222
480.0      222
392.0      220
408.0      220
4.8        219
549.0      218
2.9        218
363.0      218
364.0      218
338.0      218
587.0      217
445.0      216
2.8        216
673.0      216
563.0      215
390.0      214
463.0      213
354.0      212
543.0      212
371.0      211
2.7        210
474.0      209
548.0      205
433.0      205
616.0      205
337.0      204
398.0      203
400.0      202
541.0      202
461.0      202
430.0      201
419.0      201
1.8        200
619.0      200
529.0      200
626.0      199
374.0      199
603.0      198
3.8        195
2.3        195
575.0      194
574.0      194
537.0      193
406.0      193
394.0      193
464.0      193
460.0      192
420.0      192
562.0      191
607.0      191
577.0      191
472.0      191
447.0      190
443.0      189
366.0      189
462.0      188
454.0      187
694.0      185
1.9        184
583.0      183
542.0      183
552.0      182
367.0      182
448.0      181
580.0      179
476.0      178
441.0      178
611.0      176
382.0      176
411.0      176
479.0      175
592.0      175
591.0      175
533.0      174
648.0      174
560.0      174
470.0      174
432.0      174
3.2        173
353.0      173
381.0      172
5.8        172
567.0      172
556.0      172
457.0      171
557.0      171
0.1        170
695.0      170
450.0      170
608.0      170
551.0      169
671.0      169
578.0      169
0.2        168
565.0      168
459.0      167
372.0      167
455.0      167
606.0      167
631.0      166
564.0      166
531.0      166
1.2        166
453.0      165
4.2        165
417.0      165
375.0      165
590.0      164
359.0      164
376.0      163
604.0      162
612.0      162
451.0      162
550.0      162
660.0      161
536.0      161
468.0      161
379.0      161
600.0      161
690.0      161
595.0      160
391.0      160
368.0      159
0.3        158
3.4        158
1.3        157
708.0      157
473.0      157
19.5       157
466.0      157
588.0      156
2.4        156
566.0      155
373.0      155
668.0      154
4.3        152
589.0      152
653.0      151
572.0      151
370.0      150
5.4        149
469.0      148
569.0      148
1.7        148
544.0      148
4.7        148
3.7        148
711.0      145
730.0      145
539.0      145
568.0      145
593.0      144
449.0      144
602.0      143
672.0      143
559.0      143
6.8        142
0.8        142
1.6        141
713.0      141
16.5       141
3.9        141
2.2        141
17.5       139
45.5       139
687.0      139
67.5       139
585.0      138
547.0      138
570.0      137
7.5        136
584.0      136
664.0      136
644.0      135
650.0      135
15.5       135
4.9        133
594.0      133
674.0      133
70.8       133
70.5       133
0.6        132
599.0      131
9.9        131
838.0      131
431.0      131
721.0      131
598.0      130
471.0      130
9.5        129
4.6        129
54.4       129
582.0      129
829.0      128
723.0      128
609.0      128
750.0      128
377.0      127
810.0      127
596.0      127
613.0      127
6.5        126
702.0      126
24.5       125
5.6        125
670.0      124
5.2        123
724.0      123
678.0      123
573.0      123
704.0      123
816.0      123
729.0      122
553.0      122
629.0      122
558.0      122
610.0      121
452.0      121
51.9       121
815.0      120
46.9       120
4.1        120
540.0      119
458.0      119
4.4        119
48.5       118
7.2        118
49.9       118
630.0      117
37.5       117
538.0      117
208.5      116
715.0      116
62.9       116
576.0      116
710.0      116
712.0      115
0.7        115
16.4       115
586.0      115
581.0      115
534.0      114
827.0      114
635.0      113
722.0      112
148.3      111
5.7        110
667.0      110
681.0      110
628.0      110
666.0      110
686.0      110
467.0      109
3.3        109
58.8       109
23.5       109
718.0      109
709.0      108
669.0      108
7.8        108
804.0      108
692.0      107
554.0      107
222.6      107
627.0      107
691.0      107
57.8       107
18.9       107
118.5      107
148.9      106
12.5       106
206.8      106
22.5       106
800.0      105
10.5       105
7.9        105
719.0      104
89.7       104
42.8       104
29.5       104
725.0      104
45.9       103
640.0      103
16.8       103
47.5       103
720.0      103
62.5       103
5.1        102
679.0      102
38.1       102
0.9        102
2.1        101
697.0      101
37.8       101
1.4        101
579.0      101
8.5        100
8.9        100
654.0      100
649.0      100
10.8       100
571.0      100
705.0      100
6.9        100
192.9       99
633.0       99
555.0       99
96.5        99
48.8        98
102.3       98
66.5        98
765.0       98
209.9       97
49.5        97
643.0       96
27.5        96
665.0       96
675.0       96
18.4        96
755.0       95
51.5        95
72.5        95
877.0       95
652.0       94
520.7       94
12.4        94
169.2       94
12.8        94
651.0       93
16.2        93
645.0       93
7.6         93
44.5        93
83.4        93
832.0       92
23.8        92
25.3        92
18.5        92
7.3         92
118.9       91
68.5        91
465.0       91
12.9        91
7.7         91
942.0       91
122.9       90
38.8        90
759.0       90
23.9        90
693.0       90
26.7        90
10.9        89
26.5        89
22.1        89
41.9        89
14.9        89
831.0       89
186.7       88
905.0       88
107.5       88
54.5        88
685.0       88
136.5       88
843.0       88
24.6        87
66.3        87
6.1         87
38.5        87
42.9        87
124.5       87
55.8        87
701.0       87
13.5        87
736.0       87
0.4         86
39.6        86
11.1        86
48.3        86
146.8       86
823.0       86
101.2       86
662.0       86
75.5        86
19.8        85
127.9       85
680.0       85
10.2        85
745.0       85
45.8        85
1.1         85
785.0       85
834.0       85
145.9       85
637.0       84
212.2       84
39.8        84
739.0       84
27.8        84
21.7        84
48.2        84
36.9        84
716.0       84
149.9       84
43.5        84
13.4        84
51.6        84
656.0       84
10.1        83
85.5        83
77.5        83
6.7         83
30.2        83
226.5       83
11.5        83
12.3        83
3.1         83
751.0       83
659.0       82
228.5       82
18.8        82
41.5        82
27.9        82
8.1         81
677.0       81
22.8        81
799.0       81
120.5       81
184.5       81
137.8       81
46.5        81
62.7        81
811.0       81
47.7        81
2.6         81
5.3         81
10.3        80
42.5        80
14.8        80
634.0       80
98.1        80
696.0       80
10.6        80
47.9        80
835.0       80
778.9       80
140.5       80
215.5       80
68.1        80
53.2        80
931.0       80
147.8       80
19.2        79
19.4        79
70.6        79
37.9        79
43.8        79
13.7        79
13.8        79
82.5        79
14.5        79
7.1         79
31.8        79
9.7         79
80.5        79
31.9        79
39.7        78
703.0       78
756.0       78
149.2       78
29.9        78
50.4        78
31.7        78
525.9       78
25.2        78
11.8        78
157.2       78
726.0       78
146.6       78
657.0       78
682.0       78
191.3       78
11.9        78
177.7       78
73.5        78
8.8         77
35.3        77
21.8        77
753.0       77
73.8        77
909.0       77
83.5        77
59.9        77
84.5        77
128.6       77
175.5       77
210.8       77
63.9        77
147.9       76
15.8        76
66.6        76
639.0       76
76.5        76
36.5        76
688.0       76
12.2        76
83.7        76
700.0       76
144.2       76
473.5       76
46.7        76
81.8        75
25.5        75
37.2        75
8.4         75
658.0       75
822.0       75
767.0       75
53.5        75
731.0       75
884.0       75
122.4       75
121.5       75
206.5       74
89.5        74
214.2       74
51.8        74
69.5        74
206.9       74
19.1        74
84.3        74
48.9        74
210.6       74
15.4        74
67.7        74
126.3       73
142.9       73
57.5        73
850.0       73
81.5        73
727.0       73
67.3        73
205.5       73
88.5        73
83.1        72
8.3         72
7.4         72
31.5        72
267.9       72
632.0       72
22.9        72
689.0       72
796.0       72
298.5       72
28.5        72
305.9       72
147.5       72
801.0       72
676.0       72
81.9        72
15.3        72
40.5        72
147.2       71
144.9       71
314.8       71
32.9        71
733.0       71
75.6        71
12.7        71
864.0       71
74.5        71
16.9        71
176.8       71
601.0       71
20.5        71
82.8        71
8.6         71
282.4       71
484.5       71
754.0       71
86.9        71
45.6        70
50.8        70
655.0       70
646.0       70
46.8        70
62.2        70
23.2        70
16.6        70
18.3        70
647.0       70
50.5        70
286.5       70
146.5       70
207.5       70
735.0       70
15.6        70
202.7       70
786.0       70
50.9        70
169.5       70
75.1        70
13.9        70
21.5        69
678.9       69
29.8        69
15.9        69
802.0       69
661.0       69
777.0       69
72.3        69
99.5        69
174.5       69
10.7        69
153.3       69
261.2       69
41.7        69
65.5        69
63.8        69
49.3        69
146.9       69
760.0       69
44.4        69
970.0       69
157.8       69
14.1        69
64.5        68
478.5       68
913.0       68
17.8        68
62.3        68
97.8        68
37.4        68
740.0       68
67.9        68
200.9       68
28.3        68
19.9        68
87.7        68
103.9       68
18.7        68
789.0       68
854.0       68
45.1        68
6.6         68
752.8       68
30.5        68
144.5       68
150.5       68
116.9       68
62.8        67
49.8        67
442.5       67
698.0       67
367.9       67
138.8       67
211.2       67
123.5       67
68.9        67
803.0       67
204.5       67
143.5       67
837.0       67
813.0       67
817.0       67
145.7       67
71.5        67
31.2        67
12.1        66
151.9       66
174.2       66
58.3        66
87.1        66
63.5        66
3.6         66
20.8        66
638.0       66
792.0       66
264.5       66
663.0       66
67.6        66
210.5       66
52.3        66
642.0       66
821.0       65
43.1        65
58.9        65
78.9        65
138.5       65
13.1        65
36.2        65
839.0       65
15.7        65
509.5       65
35.5        65
32.5        65
105.5       65
734.0       65
55.5        65
24.7        65
5.9         65
8.2         65
40.2        65
111.4       64
61.8        64
38.3        64
481.5       64
61.4        64
96.4        64
40.9        64
17.9        64
86.5        64
274.9       64
52.5        64
36.8        64
586.4       64
174.8       64
938.0       64
279.5       64
34.5        64
145.5       64
101.5       64
1110.0      64
233.7       64
106.2       64
830.0       64
900.0       64
46.2        64
51.1        64
72.2        64
45.3        64
94.8        64
52.1        64
814.0       64
44.8        64
68.3        64
206.2       64
26.4        63
24.3        63
83.3        63
28.8        63
474.2       63
93.5        63
44.3        63
148.7       63
728.0       63
244.7       63
218.5       63
125.5       63
752.0       63
93.4        63
812.0       63
52.8        63
778.0       63
85.7        63
75.7        63
890.0       63
211.5       63
143.4       63
45.7        63
783.0       63
23.6        63
641.0       63
9.8         63
97.2        63
75.2        62
147.1       62
43.9        62
6.3         62
54.3        62
175.7       62
606.6       62
42.7        62
749.0       62
486.5       62
91.8        62
69.9        62
415.9       62
72.6        62
925.0       62
89.8        62
95.6        62
207.8       62
39.9        62
40.3        62
11.7        62
30.7        62
6.2         62
51.4        62
886.0       62
83.9        62
435.3       61
157.7       61
684.0       61
844.0       61
227.3       61
52.7        61
46.6        61
632.5       61
83.8        61
16.3        61
209.7       61
154.2       61
132.9       61
66.1        61
149.3       61
195.9       61
27.7        61
47.8        61
763.0       61
63.3        61
207.7       61
52.9        61
683.0       61
882.0       61
101.9       61
60.2        61
36.1        61
432.9       60
129.7       60
101.4       60
115.5       60
60.1        60
72.1        60
885.0       60
373.6       60
892.0       60
714.0       60
79.5        60
940.0       60
349.5       60
129.9       60
14.4        60
21.1        60
113.9       60
133.2       60
35.7        60
21.9        60
422.9       60
212.9       60
424.9       60
24.8        60
306.5       60
306.9       59
61.9        59
411.2       59
415.7       59
13.2        59
247.9       59
158.7       59
89.9        59

In [286]:
# printando algumas informações pertinentes que ajudam a avaliar quais transformações são necessárias
display(dataset.shape)
display(dataset.head())
display(dataset.info())
display(dataset.describe())
display(dataset.isnull().sum())

(455060, 35)

         id    pesid data_inversa     dia_semana   horario  uf   br     km           municipio                                            causa_acidente                   tipo_acidente classificacao_acidente     fase_dia  sentido_via condicao_metereologica tipo_pista   tracado_via uso_solo  id_veiculo     tipo_veiculo                   marca  ano_fabricacao_veiculo tipo_envolvido  estado_fisico  idade       sexo  ilesos  feridos_leves  feridos_graves  mortos   latitude  longitude regional delegacia             uop
0  571789.0  1269011   2024-01-01  segunda-feira  03:56:00  ES  101   38.0  CONCEICAO DA BARRA                                    Ultrapassagem Indevida  Colisão lateral sentido oposto                    NaN  Plena Noite    Crescente              Céu Claro    Simples          Reta      Não     1018240  Caminhão-trator     M.BENZ/AXOR 2544 LS                    2014       Condutor          Ileso     46  Masculino       1              0               0       0 -18.482610 -39.923790  SPRF-ES  DEL04-ES  UOP02-DEL04-ES
1  571804.0  1269118   2024-01-01  segunda-feira  04:50:00  PI  343  185.0            PIRIPIRI                               Manobra de mudança de faixa                 Colisão frontal     Com Vítimas Fatais    Amanhecer  Decrescente              Céu Claro    Simples          Reta      Sim     1018325         Caminhão       M.BENZ/ATEGO 2426                    2019       Condutor          Ileso     24  Masculino       1              0               0       0  -4.296033 -41.767327  SPRF-PI  DEL02-PI  UOP01-DEL02-PI
2  571806.0  1269735   2024-01-01  segunda-feira  04:30:00  BA  116  578.0             BREJOES                          Ingestão de álcool pelo condutor                 Colisão frontal     Com Vítimas Fatais  Plena Noite  Decrescente              Céu Claro    Simples         Curva      Não     1018705  Caminhão-trator        SCANIA/R450 A6X2                    2021       Condutor          Ileso     45  Masculino       1              0               0       0 -13.071583 -39.961111  SPRF-BA  DEL03-BA  UOP02-DEL03-BA
3  571818.0  1269075   2024-01-01  segunda-feira  06:30:00  SE  101   18.0    MALHADA DOS BOIS                  Reação tardia ou ineficiente do condutor       Saída de leito carroçável    Com Vítimas Feridas    Amanhecer    Crescente              Céu Claro      Dupla  Declive;Reta      Não     1018287  Caminhão-trator  IVECO/STRALIS 800S48TZ                    2022       Condutor  Lesões Graves     33  Masculino       0              0               1       0 -10.356019 -36.905522  SPRF-SE  DEL02-SE  UOP02-DEL02-SE
4  571838.0  1269159   2024-01-01  segunda-feira  05:00:00  MT  364  240.0        RONDONOPOLIS  Condutor deixou de manter distância do veículo da frente                Colisão traseira            Sem Vítimas    Pleno dia    Crescente              Céu Claro      Dupla          Reta      Não     1018348         Caminhão       SCANIA/P 310 B8X2                    2013       Condutor          Ileso     57  Masculino       1              0               0       0 -16.179141 -54.789053  SPRF-MT  DEL02-MT  UOP01-DEL02-MT

<class 'pandas.core.frame.DataFrame'>
Index: 455060 entries, 0 to 64124
Data columns (total 35 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      455060 non-null  float64
 1   pesid                   455060 non-null  int64
 2   data_inversa            455060 non-null  datetime64[ns]
 3   dia_semana              455060 non-null  object
 4   horario                 455060 non-null  object
 5   uf                      455060 non-null  object
 6   br                      455060 non-null  int64
 7   km                      455060 non-null  float64
 8   municipio               455060 non-null  object
 9   causa_acidente          455060 non-null  object
 10  tipo_acidente           455060 non-null  object
 11  classificacao_acidente  455045 non-null  object
 12  fase_dia                455060 non-null  object
 13  sentido_via             455060 non-null  object
 14  condicao_metereologica  455060 non-null  object
 15  tipo_pista              455060 non-null  object
 16  tracado_via             455060 non-null  object
 17  uso_solo                455060 non-null  object
 18  id_veiculo              455060 non-null  int64
 19  tipo_veiculo            440220 non-null  object
 20  marca                   455060 non-null  object
 21  ano_fabricacao_veiculo  455060 non-null  int64
 22  tipo_envolvido          415118 non-null  object
 23  estado_fisico           415118 non-null  object
 24  idade                   455060 non-null  int64
 25  sexo                    415118 non-null  object
 26  ilesos                  455060 non-null  int64
 27  feridos_leves           455060 non-null  int64
 28  feridos_graves          455060 non-null  int64
 29  mortos                  455060 non-null  int64
 30  latitude                455060 non-null  float64
 31  longitude               455060 non-null  float64
 32  regional                455037 non-null  object
 33  delegacia               454892 non-null  object
 34  uop                     454524 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(9), object(21)
memory usage: 125.0+ MB

None

                 id         pesid                   data_inversa             br             km    id_veiculo  ano_fabricacao_veiculo          idade         ilesos  feridos_leves  feridos_graves         mortos       latitude      longitude
count  455060.00000  4.550600e+05                         455060  455060.000000  455060.000000  4.550600e+05           455060.000000  455060.000000  455060.000000  455060.000000   455060.000000  455060.000000  455060.000000  455060.000000
mean   670834.11838  1.369358e+06  2025-03-04 05:03:41.161165056     211.183125     268.202186  1.160016e+06             1834.960025      33.417624       0.392267       0.327104        0.102802       0.031031     -18.648385     -46.631066
min    571772.00000  0.000000e+00            2024-01-01 00:00:00       0.000000       0.000000  0.000000e+00                0.000000       0.000000       0.000000       0.000000        0.000000       0.000000     -33.689326     -72.835751
25%    619713.00000  1.354106e+06            2024-08-04 00:00:00     101.000000      81.000000  1.101625e+06             2007.000000      21.000000       0.000000       0.000000        0.000000       0.000000     -24.982890     -50.576593
50%    665497.00000  1.479008e+06            2025-03-03 00:00:00     163.000000     203.000000  1.191750e+06             2013.000000      34.000000       0.000000       0.000000        0.000000       0.000000     -20.225260     -47.481389
75%    723575.00000  1.604566e+06            2025-10-05 00:00:00     324.000000     421.000000  1.286620e+06             2020.000000      47.000000       1.000000       1.000000        0.000000       0.000000     -12.540656     -42.466417
max    772176.00000  1.737879e+06            2026-04-30 00:00:00     495.000000    1470.000000  1.383658e+06             2026.000000    2025.000000       1.000000       1.000000        1.000000       1.000000       4.461419     -32.406822
std     58377.94562  4.431653e+05                            NaN     127.920838     231.231042  2.360007e+05              573.047374      41.071743       0.488256       0.469156        0.303700       0.173402       7.679181       6.246490

id                            0
pesid                         0
data_inversa                  0
dia_semana                    0
horario                       0
uf                            0
br                            0
km                            0
municipio                     0
causa_acidente                0
tipo_acidente                 0
classificacao_acidente       15
fase_dia                      0
sentido_via                   0
condicao_metereologica        0
tipo_pista                    0
tracado_via                   0
uso_solo                      0
id_veiculo                    0
tipo_veiculo              14840
marca                         0
ano_fabricacao_veiculo        0
tipo_envolvido            39942
estado_fisico             39942
idade                         0
sexo                      39942
ilesos                        0
feridos_leves                 0
feridos_graves                0
mortos                        0
latitude                      0
longitude                     0
regional                     23
delegacia                   168
uop                         536
dtype: int64

## Transformando a coluna ano veículo
Olhando para as informações do discribe() é possível observar que o valor mínimo é 0, ou seja veiculos sem a informação de ano, no lugar de 0 deveria existir null para não influenciar calculos de métricas posteriormente e saber da ausência de informação

In [287]:
dataset.loc[dataset["ano_fabricacao_veiculo"] == 0, "ano_fabricacao_veiculo"] = pd.NA

## Avaliando booleanos de condição física das pessoas envolvidas
Existem 4 colunas booleanas que representam a condição física da pessoa envolvida, entretanto essa mesma informação está na coluna `estado_fisico` de forma textual

In [288]:
pd.crosstab( # para verificar se realmente as informaçõs de uma coluna estão em outra
    dataset["estado_fisico"],
    [
        dataset["ilesos"],
        dataset["feridos_leves"],
        dataset["feridos_graves"],
        dataset["mortos"]
    ]
)

dataset = dataset.drop(columns=[
    "ilesos",
    "feridos_leves",
    "feridos_graves",
    "mortos"
])

## Avaliando os valores da coluna idade

Nessa coluna tem dois problemas principais:
- Quando não existe informação de qual a idade ela é preenchida como -1, é melhor fica como NULL pois deixar esse campo com -1 pode atrapalhar o calculo de métricas posteriormente como saber qual a média de idade das pessoas que sofrem acidentes
- Existem idades que são impossíveis como por exemplo maiores que 200 anos, avaliando os dados notem que existem amostras com 127 anos depois com 225 anos, apesar de idades superiores a 110 anos já serem extremamente improváveis e a pessoa mais velha registrada ter 122 anos vou considerar o limite como 127
- um ponto que provavelmente deve ser um erro, mas não tem como saber de forma 100% correta são as pessoas com 0 anos, isso poderia indicar pessoas com menos de 1 ano de idade, entretando como esse valor detem mais de 78.000 amostras enquanto a quantidade e pessoas maiores que 0 e menor ou igual a 25 anos é de aproximadamente 73.000 leva a indicar que provavelmente esses dados foram preenchidos de forma errada

In [289]:
# analisando os valores distintos dessa coluna para saber quando existem prováveis outliers
# display(dataset["idade"].value_counts().sort_index())

# analisando a quantidade de pessoas com idade igual a 0 e comparando com outro grupo
idade_0_a_25 = dataset.loc[(dataset["idade"] <= 25) & (dataset["idade"] > 0), "idade" ].count()
idade_0 = dataset.loc[dataset["idade"] == 0, "idade"].count()
print(f"Quantidade de pessoas com 0 (zero) anos de idade: {idade_0}")
print(f"Quantidade de pessoas com idades entre 1-25 anos: {idade_0_a_25}")
# apesar de ser inprovável que a quantidade de vítimas recem nascidas seja superior as de idade entre 1-25 anos não é possível dizer que isso é um erro de forma categorica

# substituindo os valores -1 por NULL
dataset.loc[dataset["idade"] == -1, "idade"] = pd.NA

# substituindo idade impossíveis
dataset.loc[dataset["idade"] > 127, "idade"] = pd.NA

Quantidade de pessoas com 0 (zero) anos de idade: 78970
Quantidade de pessoas com idades entre 1-25 anos: 73925

# Tratando a coluna classificacao_acidente
Existem alguns valores nulos nessa coluna que possivelmente podem ser passados para um tipo dentro das categorias já existentes

In [290]:
# De acordo com o dicionário de dados existe a classificação "Ignorado" para essa coluna, vamos passar os valores NULL para essa classe
dataset["classificacao_acidente"] = dataset["classificacao_acidente"].fillna("Ignorado")

# Analisando a coluna "tracado_via"
Analisar se essa coluna tem multiplos valores em uma única célula e quais são os valores possíveis

In [291]:
display(dataset["tracado_via"].unique())
"""
provavelmente vou ter que tratar essa coluna descobrindo quais são os valores atómicos usados, criar uma tabela com cada um dos tipos de traçado contendo IDs para eles e criar uma tabela ponte que
vai ligar o acidente as suas causas
"""

array(['Reta', 'Curva', 'Declive;Reta', 'Aclive;Curva', 'Reta;Declive',
       'Retorno Regulamentado', 'Curva;Declive', 'Declive;Curva',
       'Reta;Ponte', 'Aclive', 'Reta;Aclive',
       'Retorno Regulamentado;Reta', 'Viaduto', 'Curva;Viaduto',
       'Reta;Retorno Regulamentado', 'Interseção de Vias;Reta',
       'Aclive;Reta', 'Reta;Ponte;Declive',
       'Interseção de Vias;Rotatória', 'Rotatória;Reta', 'Ponte',
       'Rotatória', 'Declive', 'Interseção de Vias',
       'Curva;Em Obras;Desvio Temporário', 'Declive;Reta;Ponte',
       'Reta;Interseção de Vias;Em Obras', 'Aclive;Retorno Regulamentado',
       'Retorno Regulamentado;Reta;Interseção de Vias', 'Curva;Aclive',
       'Reta;Em Obras;Desvio Temporário', 'Curva;Aclive;Em Obras',
       'Curva;Em Obras', 'Reta;Em Obras;Ponte', 'Reta;Rotatória',
       'Curva;Interseção de Vias', 'Reta;Viaduto',
       'Declive;Interseção de Vias', 'Reta;Interseção de Vias',
       'Aclive;Rotatória;Curva', 'Aclive;Ponte;Reta',
       'Reta;Desvio Temporário', 'Curva;Declive;Ponte',
       'Rotatória;Reta;Declive',
       'Curva;Retorno Regulamentado;Interseção de Vias;Declive',
       'Reta;Retorno Regulamentado;Interseção de Vias;Rotatória',
       'Reta;Retorno Regulamentado;Interseção de Vias',
       'Rotatória;Reta;Interseção de Vias', 'Reta;Em Obras',
       'Interseção de Vias;Declive', 'Em Obras;Reta',
       'Interseção de Vias;Rotatória;Declive', 'Ponte;Reta',
       'Em Obras;Desvio Temporário',
       'Reta;Em Obras;Declive;Interseção de Vias', 'Reta;Declive;Ponte',
       'Retorno Regulamentado;Curva', 'Ponte;Declive;Curva',
       'Reta;Interseção de Vias;Aclive', 'Ponte;Reta;Declive',
       'Rotatória;Interseção de Vias', 'Curva;Aclive;Viaduto',
       'Interseção de Vias;Curva', 'Declive;Reta;Em Obras',
       'Reta;Aclive;Viaduto', 'Retorno Regulamentado;Rotatória',
       'Reta;Interseção de Vias;Desvio Temporário', 'Em Obras',
       'Interseção de Vias;Aclive', 'Rotatória;Interseção de Vias;Curva',
       'Interseção de Vias;Viaduto', 'Curva;Ponte',
       'Curva;Retorno Regulamentado;Aclive',
       'Declive;Reta;Interseção de Vias', 'Em Obras;Viaduto;Reta',
       'Rotatória;Declive', 'Em Obras;Curva',
       'Interseção de Vias;Em Obras', 'Rotatória;Curva', 'Viaduto;Curva',
       'Reta;Declive;Em Obras', 'Retorno Regulamentado;Aclive',
       'Declive;Curva;Em Obras', 'Ponte;Curva',
       'Reta;Declive;Interseção de Vias', 'Em Obras;Declive;Curva',
       'Aclive;Reta;Em Obras;Desvio Temporário',
       'Declive;Retorno Regulamentado;Curva', 'Viaduto;Reta',
       'Curva;Desvio Temporário;Aclive', 'Em Obras;Declive;Reta',
       'Aclive;Viaduto', 'Desvio Temporário;Aclive;Reta',
       'Aclive;Ponte;Curva', 'Aclive;Interseção de Vias;Reta',
       'Túnel;Reta', 'Declive;Ponte',
       'Interseção de Vias;Retorno Regulamentado;Rotatória',
       'Desvio Temporário', 'Em Obras;Curva;Declive',
       'Túnel;Curva;Retorno Regulamentado',
       'Ponte;Em Obras;Curva;Declive;Desvio Temporário',
       'Curva;Interseção de Vias;Rotatória', 'Declive;Ponte;Reta',
       'Viaduto;Aclive;Reta', 'Interseção de Vias;Reta;Declive',
       'Ponte;Curva;Declive', 'Retorno Regulamentado;Interseção de Vias',
       'Declive;Rotatória;Curva', 'Em Obras;Curva;Interseção de Vias',
       'Retorno Regulamentado;Declive;Interseção de Vias;Reta',
       'Viaduto;Reta;Retorno Regulamentado', 'Aclive;Reta;Em Obras',
       'Reta;Declive;Rotatória', 'Interseção de Vias;Declive;Reta',
       'Declive;Desvio Temporário', 'Ponte;Declive',
       'Aclive;Reta;Interseção de Vias',
       'Interseção de Vias;Retorno Regulamentado',
       'Curva;Rotatória;Interseção de Vias', 'Túnel;Reta;Declive',
       'Curva;Ponte;Em Obras',
       'Em Obras;Interseção de Vias;Desvio Temporário',
       'Retorno Regulamentado;Interseção de Vias;Reta',
       'Viaduto;Reta;Aclive', 'Reta;Viaduto;Interseção de Vias',
       'Desvio Temporário;Em Obras;Aclive', 'Curva;Rotatória',
       'Desvio Temporário;Reta;Em Obras',
       'Interseção de Vias;Curva;Viaduto', 'Declive;Em Obras;Reta',
       'Em Obras;Declive;Curva;Desvio Temporário',
       'Interseção de Vias;Reta;Viaduto;Retorno Regulamentado',
       'Curva;Declive;Em Obras', 'Desvio Temporário;Aclive;Em Obras',
       'Declive;Desvio Temporário;Curva',
       'Interseção de Vias;Rotatória;Reta', 'Declive;Em Obras;Curva',
       'Aclive;Rotatória', 'Aclive;Interseção de Vias',
       'Em Obras;Rotatória', 'Reta;Interseção de Vias;Declive',
       'Aclive;Retorno Regulamentado;Curva', 'Aclive;Em Obras;Reta',
       'Curva;Rotatória;Aclive;Interseção de Vias',
       'Em Obras;Reta;Declive;Desvio Temporário',
       'Interseção de Vias;Rotatória;Curva', 'Viaduto;Aclive',
       'Curva;Retorno Regulamentado;Declive;Em Obras',
       'Reta;Desvio Temporário;Em Obras', 'Reta;Aclive;Em Obras',
       'Curva;Aclive;Interseção de Vias', 'Reta;Aclive;Ponte',
       'Reta;Interseção de Vias;Viaduto',
       'Declive;Retorno Regulamentado;Reta', 'Reta;Em Obras;Declive',
       'Interseção de Vias;Retorno Regulamentado;Reta',
       'Em Obras;Desvio Temporário;Reta', 'Aclive;Reta;Viaduto',
       'Declive;Rotatória;Interseção de Vias',
       'Reta;Aclive;Interseção de Vias',
       'Retorno Regulamentado;Declive;Reta', 'Aclive;Viaduto;Reta',
       'Ponte;Reta;Em Obras', 'Declive;Interseção de Vias;Rotatória',
       'Desvio Temporário;Curva;Em Obras',
       'Rotatória;Interseção de Vias;Reta', 'Viaduto;Aclive;Curva',
       'Reta;Em Obras;Aclive', 'Em Obras;Declive',
       'Reta;Interseção de Vias;Retorno Regulamentado',
       'Retorno Regulamentado;Reta;Em Obras',
       'Desvio Temporário;Em Obras',
       'Viaduto;Interseção de Vias;Reta;Declive',
       'Rotatória;Interseção de Vias;Retorno Regulamentado;Reta',
       'Em Obras;Reta;Viaduto', 'Reta;Declive;Rotatória;Viaduto',
       'Aclive;Em Obras', 'Declive;Interseção de Vias;Curva',
       'Declive;Ponte;Curva', 'Reta;Declive;Viaduto', 'Reta;Ponte;Aclive',
       'Curva;Retorno Regulamentado', 'Em Obras;Ponte',
       'Reta;Interseção de Vias;Rotatória',
       'Reta;Declive;Retorno Regulamentado',
       'Curva;Declive;Interseção de Vias',
       'Interseção de Vias;Retorno Regulamentado;Curva',
       'Interseção de Vias;Ponte', 'Em Obras;Desvio Temporário;Curva',
       'Reta;Viaduto;Declive', 'Em Obras;Aclive;Reta',
       'Interseção de Vias;Declive;Curva',
       'Reta;Retorno Regulamentado;Aclive',
       'Interseção de Vias;Declive;Rotatória',
       'Aclive;Desvio Temporário;Curva', 'Viaduto;Reta;Declive',
       'Viaduto;Rotatória', 'Em Obras;Desvio Temporário;Curva;Aclive',
       'Curva;Declive;Viaduto',
       'Rotatória;Desvio Temporário;Declive;Interseção de Vias;Em Obras;Reta',
       'Em Obras;Reta;Interseção de Vias',
       'Declive;Interseção de Vias;Reta',
       'Retorno Regulamentado;Curva;Aclive',
       'Interseção de Vias;Em Obras;Reta',
       'Interseção de Vias;Reta;Retorno Regulamentado',
       'Retorno Regulamentado;Declive;Curva', 'Em Obras;Ponte;Reta',
       'Desvio Temporário;Reta',
       'Interseção de Vias;Reta;Viaduto;Declive', 'Declive;Viaduto',
       'Reta;Em Obras;Interseção de Vias', 'Em Obras;Reta;Declive',
       'Curva;Retorno Regulamentado;Declive', 'Declive;Rotatória',
       'Curva;Interseção de Vias;Em Obras', 'Curva;Ponte;Declive',
       'Em Obras;Curva;Ponte', 'Declive;Desvio Temporário;Reta',
       'Curva;Ponte;Aclive', 'Desvio Temporário;Em Obras;Reta',
       'Em Obras;Viaduto;Aclive',
       'Curva;Desvio Temporário;Interseção de Vias',
       'Declive;Curva;Ponte',
       'Retorno Regulamentado;Rotatória;Interseção de Vias',
       'Rotatória;Viaduto;Reta', 'Declive;Em Obras',
       'Em Obras;Interseção de Vias;Curva',
       'Rotatória;Retorno Regulamentado;Viaduto',
       'Interseção de Vias;Curva;Rotatória;Retorno Regulamentado',
       'Declive;Retorno Regulamentado',
       'Interseção de Vias;Em Obras;Declive;Reta',
       'Interseção de Vias;Aclive;Reta', 'Desvio Temporário;Declive',
       'Declive;Desvio Temporário;Em Obras;Curva', 'Ponte;Aclive',
       'Curva;Túnel', 'Retorno Regulamentado;Viaduto',
       'Rotatória;Em Obras',
       'Interseção de Vias;Rotatória;Retorno Regulamentado;Reta',
       'Retorno Regulamentado;Aclive;Reta', 'Declive;Viaduto;Reta',
       'Em Obras;Interseção de Vias',
       'Interseção de Vias;Rotatória;Aclive', 'Declive;Curva;Viaduto',
       'Rotatória;Viaduto', 'Viaduto;Interseção de Vias',
       'Ponte;Declive;Reta', 'Ponte;Aclive;Reta',
       'Em Obras;Retorno Regulamentado;Reta',
       'Aclive;Retorno Regulamentado;Curva;Interseção de Vias',
       'Viaduto;Reta;Em Obras', 'Em Obras;Retorno Regulamentado',
       'Viaduto;Curva;Rotatória', 'Reta;Túnel;Declive',
       'Aclive;Interseção de Vias;Curva', 'Curva;Viaduto;Declive',
       'Interseção de Vias;Reta;Rotatória',
       'Rotatória;Curva;Interseção de Vias;Retorno Regulamentado',
       'Em Obras;Reta;Aclive', 'Em Obras;Aclive;Curva',
       'Viaduto;Declive;Interseção de Vias', 'Em Obras;Viaduto;Curva',
       'Reta;Aclive;Retorno Regulamentado', 'Em Obras;Declive;Ponte',
       'Rotatória;Interseção de Vias;Viaduto',
       'Reta;Em Obras;Viaduto;Rotatória', 'Declive;Reta;Em Obras;Ponte',
       'Reta;Viaduto;Aclive', 'Em Obras;Ponte;Reta;Desvio Temporário',
       'Curva;Desvio Temporário;Em Obras', 'Viaduto;Declive',
       'Declive;Reta;Retorno Regulamentado', 'Curva;Aclive;Rotatória',
       'Rotatória;Aclive', 'Viaduto;Declive;Reta',
       'Curva;Interseção de Vias;Aclive', 'Interseção de Vias;Túnel',
       'Declive;Viaduto;Reta;Interseção de Vias;Rotatória',
       'Interseção de Vias;Curva;Aclive',
       'Reta;Retorno Regulamentado;Rotatória', 'Viaduto;Declive;Curva',
       'Em Obras;Rotatória;Reta', 'Túnel',
       'Interseção de Vias;Reta;Declive;Rotatória;Em Obras',
       'Em Obras;Aclive',
       'Interseção de Vias;Declive;Retorno Regulamentado;Curva',
       'Rotatória;Retorno Regulamentado',
       'Reta;Rotatória;Interseção de Vias',
       'Curva;Desvio Temporário;Declive', 'Ponte;Reta;Aclive',
       'Reta;Rotatória;Viaduto', 'Em Obras;Curva;Aclive',
       'Declive;Reta;Em Obras;Desvio Temporário',
       'Em Obras;Reta;Interseção de Vias;Declive',
       'Retorno Regulamentado;Reta;Declive', 'Desvio Temporário;Curva',
       'Viaduto;Curva;Aclive',
       'Rotatória;Retorno Regulamentado;Interseção de Vias;Declive',
       'Rotatória;Em Obras;Reta', 'Rotatória;Interseção de Vias;Em Obras',
       'Aclive;Túnel;Reta',
       'Curva;Retorno Regulamentado;Interseção de Vias;Aclive',
       'Declive;Curva;Rotatória', 'Ponte;Em Obras;Reta',
       'Interseção de Vias;Viaduto;Declive;Reta',
       'Retorno Regulamentado;Reta;Aclive',
       'Interseção de Vias;Declive;Reta;Em Obras',
       'Reta;Interseção de Vias;Em Obras;Declive',
       'Aclive;Curva;Retorno Regulamentado',
       'Interseção de Vias;Reta;Aclive',
       'Em Obras;Interseção de Vias;Reta',
       'Em Obras;Reta;Desvio Temporário',
       'Desvio Temporário;Em Obras;Curva',
       'Retorno Regulamentado;Interseção de Vias;Viaduto',
       'Túnel;Reta;Aclive', 'Declive;Retorno Regulamentado;Curva;Viaduto',
       'Curva;Interseção de Vias;Viaduto',
       'Aclive;Curva;Interseção de Vias',
       'Declive;Curva;Retorno Regulamentado', 'Ponte;Interseção de Vias',
       'Em Obras;Retorno Regulamentado;Curva;Rotatória',
       'Aclive;Curva;Interseção de Vias;Viaduto;Rotatória',
       'Declive;Em Obras;Desvio Temporário',
       'Declive;Desvio Temporário;Em Obras',
       'Retorno Regulamentado;Curva;Interseção de Vias;Viaduto',
       'Reta;Retorno Regulamentado;Declive',
       'Retorno Regulamentado;Aclive;Curva', 'Declive;Ponte;Em Obras',
       'Ponte;Aclive;Curva', 'Reta;Interseção de Vias;Rotatória;Aclive',
       'Interseção de Vias;Rotatória;Viaduto', 'Curva;Em Obras;Declive',
       'Aclive;Interseção de Vias;Rotatória;Reta',
       'Rotatória;Declive;Interseção de Vias', 'Aclive;Reta;Rotatória',
       'Declive;Curva;Em Obras;Desvio Temporário',
       'Reta;Declive;Interseção de Vias;Viaduto',
       'Ponte;Reta;Desvio Temporário', 'Curva;Em Obras;Ponte',
       'Retorno Regulamentado;Curva;Viaduto',
       'Rotatória;Reta;Declive;Interseção de Vias;Viaduto',
       'Curva;Declive;Viaduto;Interseção de Vias',
       'Reta;Desvio Temporário;Ponte', 'Declive;Reta;Em Obras;Viaduto',
       'Aclive;Reta;Retorno Regulamentado;Interseção de Vias',
       'Viaduto;Curva;Retorno Regulamentado', 'Aclive;Curva;Em Obras',
       'Viaduto;Retorno Regulamentado;Curva',
       'Reta;Declive;Retorno Regulamentado;Interseção de Vias',
       'Curva;Desvio Temporário', 'Aclive;Curva;Viaduto',
       'Curva;Aclive;Desvio Temporário;Em Obras',
       'Interseção de Vias;Curva;Declive',
       'Curva;Interseção de Vias;Declive',
       'Em Obras;Declive;Desvio Temporário;Curva',
       'Declive;Rotatória;Reta', 'Em Obras;Curva;Desvio Temporário',
       'Aclive;Em Obras;Curva', 'Curva;Retorno Regulamentado;Viaduto',
       'Em Obras;Reta;Retorno Regulamentado',
       'Interseção de Vias;Rotatória;Em Obras',
       'Reta;Em Obras;Rotatória;Retorno Regulamentado',
       'Interseção de Vias;Viaduto;Reta', 'Interseção de Vias;Ponte;Reta',
       'Curva;Viaduto;Aclive',
       'Rotatória;Curva;Declive;Retorno Regulamentado',
       'Em Obras;Retorno Regulamentado;Rotatória;Interseção de Vias',
       'Desvio Temporário;Declive;Em Obras;Reta',
       'Em Obras;Declive;Desvio Temporário;Reta', 'Túnel;Curva;Declive',
       'Declive;Retorno Regulamentado;Interseção de Vias',
       'Viaduto;Retorno Regulamentado',
       'Reta;Rotatória;Retorno Regulamentado',
       'Aclive;Interseção de Vias;Retorno Regulamentado',
       'Viaduto;Aclive;Interseção de Vias;Curva;Retorno Regulamentado',
       'Curva;Rotatória;Declive', 'Desvio Temporário;Ponte;Em Obras;Reta',
       'Declive;Curva;Interseção de Vias',
       'Viaduto;Interseção de Vias;Reta',
       'Curva;Viaduto;Interseção de Vias',
       'Aclive;Em Obras;Interseção de Vias;Curva',
       'Reta;Rotatória;Em Obras',
       'Em Obras;Aclive;Curva;Desvio Temporário',
       'Rotatória;Curva;Interseção de Vias',
       'Interseção de Vias;Desvio Temporário',
       'Rotatória;Viaduto;Interseção de Vias',
       'Em Obras;Retorno Regulamentado;Curva', 'Viaduto;Rotatória;Reta',
       'Em Obras;Interseção de Vias;Retorno Regulamentado',
       'Em Obras;Ponte;Desvio Temporário',
       'Rotatória;Aclive;Curva;Viaduto',
       'Viaduto;Reta;Interseção de Vias',
       'Declive;Rotatória;Retorno Regulamentado;Reta;Interseção de Vias',
       'Interseção de Vias;Curva;Rotatória',
       'Viaduto;Interseção de Vias;Rotatória', 'Rotatória;Reta;Aclive',
       'Aclive;Interseção de Vias;Curva;Retorno Regulamentado',
       'Declive;Interseção de Vias;Em Obras;Curva',
       'Retorno Regulamentado;Aclive;Interseção de Vias;Reta',
       'Em Obras;Aclive;Rotatória;Reta',
       'Interseção de Vias;Aclive;Rotatória',
       'Retorno Regulamentado;Declive', 'Reta;Aclive;Desvio Temporário',
       'Em Obras;Interseção de Vias;Curva;Rotatória',
       'Interseção de Vias;Rotatória;Reta;Retorno Regulamentado',
       'Aclive;Viaduto;Curva',
       'Interseção de Vias;Viaduto;Retorno Regulamentado',
       'Curva;Declive;Retorno Regulamentado',
       'Em Obras;Declive;Reta;Viaduto', 'Ponte;Interseção de Vias;Reta',
       'Ponte;Curva;Em Obras;Aclive',
       'Interseção de Vias;Viaduto;Declive',
       'Declive;Retorno Regulamentado;Reta;Interseção de Vias',
       'Interseção de Vias;Em Obras;Reta;Retorno Regulamentado',
       'Desvio Temporário;Em Obras;Reta;Aclive', 'Declive;Viaduto;Curva',
       'Desvio Temporário;Reta;Declive;Em Obras',
       'Rotatória;Reta;Interseção de Vias;Declive',
       'Viaduto;Curva;Ponte;Interseção de Vias',
       'Desvio Temporário;Declive;Curva',
       'Interseção de Vias;Rotatória;Retorno Regulamentado;Curva',
       'Rotatória;Em Obras;Interseção de Vias;Viaduto', 'Viaduto;Túnel',
       'Declive;Reta;Viaduto',
       'Interseção de Vias;Rotatória;Viaduto;Curva',
       'Interseção de Vias;Reta;Em Obras;Viaduto', 'Em Obras;Reta;Ponte',
       'Curva;Aclive;Rotatória;Interseção de Vias',
       'Em Obras;Declive;Reta;Interseção de Vias',
       'Interseção de Vias;Reta;Em Obras;Aclive;Retorno Regulamentado',
       'Interseção de Vias;Curva;Declive;Viaduto',
       'Declive;Desvio Temporário;Reta;Em Obras',
       'Interseção de Vias;Reta;Em Obras',
       'Interseção de Vias;Retorno Regulamentado;Em Obras',
       'Rotatória;Viaduto;Interseção de Vias;Reta',
       'Retorno Regulamentado;Curva;Declive',
       'Reta;Interseção de Vias;Aclive;Viaduto',
       'Retorno Regulamentado;Aclive;Interseção de Vias;Rotatória;Curva',
       'Retorno Regulamentado;Aclive;Reta;Em Obras',
       'Interseção de Vias;Retorno Regulamentado;Aclive',
       'Interseção de Vias;Retorno Regulamentado;Declive;Curva',
       'Desvio Temporário;Declive;Reta;Em Obras',
       'Aclive;Retorno Regulamentado;Reta',
       'Reta;Interseção de Vias;Retorno Regulamentado;Rotatória',
       'Retorno Regulamentado;Em Obras;Curva',
       'Reta;Desvio Temporário;Em Obras;Viaduto',
       'Interseção de Vias;Retorno Regulamentado;Túnel',
       'Interseção de Vias;Retorno Regulamentado;Desvio Temporário;Em Obras',
       'Aclive;Rotatória;Retorno Regulamentado;Reta',
       'Reta;Interseção de Vias;Em Obras;Desvio Temporário',
       'Reta;Desvio Temporário;Em Obras;Declive;Viaduto',
       'Viaduto;Curva;Interseção de Vias;Rotatória',
       'Rotatória;Viaduto;Curva', 'Viaduto;Interseção de Vias;Em Obras',
       'Desvio Temporário;Reta;Em Obras;Aclive',
       'Retorno Regulamentado;Interseção de Vias;Rotatória',
       'Reta;Aclive;Interseção de Vias;Viaduto', 'Viaduto;Curva;Declive',
       'Túnel;Curva',
       'Reta;Interseção de Vias;Retorno Regulamentado;Aclive',
       'Viaduto;Aclive;Interseção de Vias',
       'Em Obras;Rotatória;Viaduto;Curva',
       'Reta;Desvio Temporário;Em Obras;Declive',
       'Desvio Temporário;Em Obras;Viaduto;Interseção de Vias',
       'Retorno Regulamentado;Rotatória;Curva',
       'Rotatória;Em Obras;Retorno Regulamentado;Interseção de Vias',
       'Viaduto;Em Obras',
       'Em Obras;Desvio Temporário;Curva;Declive;Interseção de Vias',
       'Rotatória;Retorno Regulamentado;Reta;Interseção de Vias',
       'Ponte;Reta;Declive;Desvio Temporário;Em Obras',
       'Desvio Temporário;Reta;Ponte;Em Obras',
       'Curva;Viaduto;Interseção de Vias;Declive',
       'Viaduto;Curva;Declive;Interseção de Vias',
       'Reta;Rotatória;Declive',
       'Declive;Interseção de Vias;Em Obras;Reta',
       'Interseção de Vias;Em Obras;Desvio Temporário',
       'Reta;Aclive;Rotatória',
       'Reta;Declive;Interseção de Vias;Viaduto;Em Obras',
       'Retorno Regulamentado;Interseção de Vias;Em Obras',
       'Retorno Regulamentado;Reta;Interseção de Vias;Declive',
       'Declive;Em Obras;Viaduto;Reta', 'Reta;Ponte;Em Obras',
       'Rotatória;Reta;Retorno Regulamentado', 'Ponte;Viaduto;Reta',
       'Curva;Viaduto;Rotatória;Interseção de Vias',
       'Declive;Desvio Temporário;Em Obras;Reta',
       'Aclive;Reta;Retorno Regulamentado',
       'Retorno Regulamentado;Viaduto;Interseção de Vias',
       'Rotatória;Interseção de Vias;Viaduto;Retorno Regulamentado',
       'Retorno Regulamentado;Viaduto;Curva',
       'Interseção de Vias;Reta;Viaduto',
       'Reta;Declive;Interseção de Vias;Viaduto;Retorno Regulamentado',
       'Curva;Aclive;Retorno Regulamentado',
       'Rotatória;Retorno Regulamentado;Interseção de Vias',
       'Desvio Temporário;Em Obras;Viaduto',
       'Reta;Em Obras;Interseção de Vias;Desvio Temporário',
       'Em Obras;Declive;Retorno Regulamentado;Reta',
       'Declive;Interseção de Vias;Reta;Em Obras',
       'Desvio Temporário;Rotatória;Interseção de Vias;Em Obras;Retorno Regulamentado;Viaduto',

'\nprovavelmente vou ter que tratar essa coluna descobrindo quais são os valores atómicos usados, criar uma tabela com cada um dos tipos de traçado contendo IDs para eles e criar uma tabela ponte que\nvai ligar o acidente as suas causas\n'

## Tratando os valores nulos das colunas: tipo_envolvido, stado_fisico e sexo
Como cada uma dessas colunas contem a mesma quantidade de valores nulos pode ser que sejam exatamente a mesma linha que não contem multiplas informações, uma pessoa que não contem nenhuma dessas informações pode ser caracterizada como não identificada para facilitar o entendimento das informações

In [292]:
# verificando se realmente é a mesma linha com multiplas linhas colunas vazia
filtro = (
    dataset["estado_fisico"].isna() &
    dataset["tipo_envolvido"].isna() &
    dataset["sexo"].isna()
)
print(f"quantidade de linhas que não tem informação nas colunas em questão: {filtro.sum()}")

# agora que foi mostrado que são a mesma linha vou avaliar qual a idade descrita, levando em consideração que essa é a ultima informação que sobre referente a pessoa envolvida
print(f"desas linhas quais as idades das pessoas em questão: {dataset.loc[filtro, "idade"].unique()}")

# avaliando quantos pesid distintos existem para essa pessoa
print(f"quantidade de pesid existentes para cada uma dessas linhas: {dataset.loc[filtro, "pesid"].nunique()}")

# avaliando quantos id_veiculo distintos existem para essa pessoa
print(f"quantidade de id_veiculo existentes para cada uma dessas linhas: {dataset.loc[filtro, "id_veiculo"].nunique()}")

# avaliando o tipo do veiculo envolvido pera essas pessoas
print(f"quantidade de veiculos sem tipo definido para essas pessoas: {dataset.loc[filtro, "tipo_veiculo"].isna().sum()}")

# aparentemente quando uma pessoa não é identificada ela é colocada como um ID específico e com os valores nulos nessas respectivas colunas e idade igual a 0 (zero)
# criando uma coluna nova que vai dizer se a pessoa em questão foi ou não identificada para facilitar o entendimento dos dados
dataset["identificada"] = 1
dataset.loc[filtro, "identificada"] = 0

quantidade de linhas que não tem informação nas colunas em questão: 39942
desas linhas quais as idades das pessoas em questão: [0.]
quantidade de pesid existentes para cada uma dessas linhas: 1
quantidade de id_veiculo existentes para cada uma dessas linhas: 39942
quantidade de veiculos sem tipo definido para essas pessoas: 0

In [293]:
# printando algumas informações pertinentes que ajudam a avaliar quais transformações são necessárias
display(dataset.shape)
display(dataset.head())
display(dataset.info())
display(dataset.describe())
display(dataset.isnull().sum())

(455060, 32)

         id    pesid data_inversa     dia_semana   horario  uf   br     km           municipio                                            causa_acidente                   tipo_acidente classificacao_acidente     fase_dia  sentido_via condicao_metereologica tipo_pista   tracado_via uso_solo  id_veiculo     tipo_veiculo                   marca  ano_fabricacao_veiculo tipo_envolvido  estado_fisico  idade       sexo   latitude  longitude regional delegacia             uop  identificada
0  571789.0  1269011   2024-01-01  segunda-feira  03:56:00  ES  101   38.0  CONCEICAO DA BARRA                                    Ultrapassagem Indevida  Colisão lateral sentido oposto               Ignorado  Plena Noite    Crescente              Céu Claro    Simples          Reta      Não     1018240  Caminhão-trator     M.BENZ/AXOR 2544 LS                  2014.0       Condutor          Ileso   46.0  Masculino -18.482610 -39.923790  SPRF-ES  DEL04-ES  UOP02-DEL04-ES             1
1  571804.0  1269118   2024-01-01  segunda-feira  04:50:00  PI  343  185.0            PIRIPIRI                               Manobra de mudança de faixa                 Colisão frontal     Com Vítimas Fatais    Amanhecer  Decrescente              Céu Claro    Simples          Reta      Sim     1018325         Caminhão       M.BENZ/ATEGO 2426                  2019.0       Condutor          Ileso   24.0  Masculino  -4.296033 -41.767327  SPRF-PI  DEL02-PI  UOP01-DEL02-PI             1
2  571806.0  1269735   2024-01-01  segunda-feira  04:30:00  BA  116  578.0             BREJOES                          Ingestão de álcool pelo condutor                 Colisão frontal     Com Vítimas Fatais  Plena Noite  Decrescente              Céu Claro    Simples         Curva      Não     1018705  Caminhão-trator        SCANIA/R450 A6X2                  2021.0       Condutor          Ileso   45.0  Masculino -13.071583 -39.961111  SPRF-BA  DEL03-BA  UOP02-DEL03-BA             1
3  571818.0  1269075   2024-01-01  segunda-feira  06:30:00  SE  101   18.0    MALHADA DOS BOIS                  Reação tardia ou ineficiente do condutor       Saída de leito carroçável    Com Vítimas Feridas    Amanhecer    Crescente              Céu Claro      Dupla  Declive;Reta      Não     1018287  Caminhão-trator  IVECO/STRALIS 800S48TZ                  2022.0       Condutor  Lesões Graves   33.0  Masculino -10.356019 -36.905522  SPRF-SE  DEL02-SE  UOP02-DEL02-SE             1
4  571838.0  1269159   2024-01-01  segunda-feira  05:00:00  MT  364  240.0        RONDONOPOLIS  Condutor deixou de manter distância do veículo da frente                Colisão traseira            Sem Vítimas    Pleno dia    Crescente              Céu Claro      Dupla          Reta      Não     1018348         Caminhão       SCANIA/P 310 B8X2                  2013.0       Condutor          Ileso   57.0  Masculino -16.179141 -54.789053  SPRF-MT  DEL02-MT  UOP01-DEL02-MT             1

<class 'pandas.core.frame.DataFrame'>
Index: 455060 entries, 0 to 64124
Data columns (total 32 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      455060 non-null  float64
 1   pesid                   455060 non-null  int64
 2   data_inversa            455060 non-null  datetime64[ns]
 3   dia_semana              455060 non-null  object
 4   horario                 455060 non-null  object
 5   uf                      455060 non-null  object
 6   br                      455060 non-null  int64
 7   km                      455060 non-null  float64
 8   municipio               455060 non-null  object
 9   causa_acidente          455060 non-null  object
 10  tipo_acidente           455060 non-null  object
 11  classificacao_acidente  455060 non-null  object
 12  fase_dia                455060 non-null  object
 13  sentido_via             455060 non-null  object
 14  condicao_metereologica  455060 non-null  object
 15  tipo_pista              455060 non-null  object
 16  tracado_via             455060 non-null  object
 17  uso_solo                455060 non-null  object
 18  id_veiculo              455060 non-null  int64
 19  tipo_veiculo            440220 non-null  object
 20  marca                   455060 non-null  object
 21  ano_fabricacao_veiculo  414630 non-null  float64
 22  tipo_envolvido          415118 non-null  object
 23  estado_fisico           415118 non-null  object
 24  idade                   454742 non-null  float64
 25  sexo                    415118 non-null  object
 26  latitude                455060 non-null  float64
 27  longitude               455060 non-null  float64
 28  regional                455037 non-null  object
 29  delegacia               454892 non-null  object
 30  uop                     454524 non-null  object
 31  identificada            455060 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(4), object(21)
memory usage: 114.6+ MB

None

                 id         pesid                   data_inversa             br             km    id_veiculo  ano_fabricacao_veiculo          idade       latitude      longitude   identificada
count  455060.00000  4.550600e+05                         455060  455060.000000  455060.000000  4.550600e+05           414630.000000  454742.000000  455060.000000  455060.000000  455060.000000
mean   670834.11838  1.369358e+06  2025-03-04 05:03:41.161165056     211.183125     268.202186  1.160016e+06             2013.884449      32.557024     -18.648385     -46.631066       0.912227
min    571772.00000  0.000000e+00            2024-01-01 00:00:00       0.000000       0.000000  0.000000e+00             1900.000000       0.000000     -33.689326     -72.835751       0.000000
25%    619713.00000  1.354106e+06            2024-08-04 00:00:00     101.000000      81.000000  1.101625e+06             2009.000000      21.000000     -24.982890     -50.576593       1.000000
50%    665497.00000  1.479008e+06            2025-03-03 00:00:00     163.000000     203.000000  1.191750e+06             2014.000000      34.000000     -20.225260     -47.481389       1.000000
75%    723575.00000  1.604566e+06            2025-10-05 00:00:00     324.000000     421.000000  1.286620e+06             2021.000000      47.000000     -12.540656     -42.466417       1.000000
max    772176.00000  1.737879e+06            2026-04-30 00:00:00     495.000000    1470.000000  1.383658e+06             2026.000000     127.000000       4.461419     -32.406822       1.000000
std     58377.94562  4.431653e+05                            NaN     127.920838     231.231042  2.360007e+05                8.341989      20.563964       7.679181       6.246490       0.282965

id                            0
pesid                         0
data_inversa                  0
dia_semana                    0
horario                       0
uf                            0
br                            0
km                            0
municipio                     0
causa_acidente                0
tipo_acidente                 0
classificacao_acidente        0
fase_dia                      0
sentido_via                   0
condicao_metereologica        0
tipo_pista                    0
tracado_via                   0
uso_solo                      0
id_veiculo                    0
tipo_veiculo              14840
marca                         0
ano_fabricacao_veiculo    40430
tipo_envolvido            39942
estado_fisico             39942
idade                       318
sexo                      39942
latitude                      0
longitude                     0
regional                     23
delegacia                   168
uop                         536
identificada                  0
dtype: int64