In [2]:
import pandas as pd
import os
from pprint import pprint

# ajustando algumas configurações para prints
pd.set_option('display.max_columns', None)        # todas as colunas
pd.set_option('display.max_rows', None)           # todas as linhas
pd.set_option('display.width', None)              # largura automática
pd.set_option('display.max_colwidth', None)       # conteúdo completo das células
pd.set_option('display.expand_frame_repr', False) # evita quebrar dataframe em várias linhas

In [3]:
# pegando a pasta de trabalho para poder extrair os dados do dataset
PASTA_TRABALHO = os.path.dirname(os.path.abspath(os.getcwd()))

## Lendo e armazenando todas as tabelas dos anos necessários

In [4]:
# lista com os nomes das pastas que contem os datasets
nomes_arquivos = ["2024", "2025", "2026"]

# dicionario que contêm todos os dataframes do respectivo ano no seguinte formato:
"""
    ano1:
        ocorrencia_ano1,
        acorrencia_pessoa_ano1,
        acorrencia_todas_causas_ano1
    ano2:
        ...
"""
dataframes_por_ano = {}

# percorre e salva todos as dataframes dos anos escolhidos
for ano in nomes_arquivos:
    diretorio_dataframe = os.path.join(PASTA_TRABALHO, "dataset", ano)

    # percorre todas as tabelas que existem nesse ano (só existe um arquivo)
    for tabela in os.listdir(diretorio_dataframe):

        caminho = os.path.join(diretorio_dataframe, tabela)
        data_frame = pd.read_csv(caminho, sep=";", encoding="latin1") # adiciona a tabela em questão ao dicionário temporário

    dataframes_por_ano[ano] = data_frame # adiciona a tabela de dados ao respectivo ano

## juntando as tabelas distintas dos 3 anos em somente uma tabela

In [5]:
dataset = pd.concat([df for df in dataframes_por_ano.values()])
display(dataset.head())
display(dataset.info())
display(data_frame.describe())
display(data_frame.isnull().sum())

         id    pesid data_inversa     dia_semana   horario  uf   br   km           municipio                                            causa_acidente                   tipo_acidente classificacao_acidente     fase_dia  sentido_via condicao_metereologica tipo_pista   tracado_via uso_solo  id_veiculo     tipo_veiculo                   marca  ano_fabricacao_veiculo tipo_envolvido  estado_fisico  idade       sexo  ilesos  feridos_leves  feridos_graves  mortos   latitude  longitude regional delegacia             uop
0  571789.0  1269011   2024-01-01  segunda-feira  03:56:00  ES  101   38  CONCEICAO DA BARRA                                    Ultrapassagem Indevida  Colisão lateral sentido oposto                    NaN  Plena Noite    Crescente              Céu Claro    Simples          Reta      Não     1018240  Caminhão-trator     M.BENZ/AXOR 2544 LS                    2014       Condutor          Ileso     46  Masculino       1              0               0       0  -18.48261  -39.92379  SPRF-ES  DEL04-ES  UOP02-DEL04-ES
1  571804.0  1269118   2024-01-01  segunda-feira  04:50:00  PI  343  185            PIRIPIRI                               Manobra de mudança de faixa                 Colisão frontal     Com Vítimas Fatais    Amanhecer  Decrescente              Céu Claro    Simples          Reta      Sim     1018325         Caminhão       M.BENZ/ATEGO 2426                    2019       Condutor          Ileso     24  Masculino       1              0               0       0  -4.296033 -41.767327  SPRF-PI  DEL02-PI  UOP01-DEL02-PI
2  571806.0  1269735   2024-01-01  segunda-feira  04:30:00  BA  116  578             BREJOES                          Ingestão de álcool pelo condutor                 Colisão frontal     Com Vítimas Fatais  Plena Noite  Decrescente              Céu Claro    Simples         Curva      Não     1018705  Caminhão-trator        SCANIA/R450 A6X2                    2021       Condutor          Ileso     45  Masculino       1              0               0       0 -13.071583 -39.961111  SPRF-BA  DEL03-BA  UOP02-DEL03-BA
3  571818.0  1269075   2024-01-01  segunda-feira  06:30:00  SE  101   18    MALHADA DOS BOIS                  Reação tardia ou ineficiente do condutor       Saída de leito carroçável    Com Vítimas Feridas    Amanhecer    Crescente              Céu Claro      Dupla  Declive;Reta      Não     1018287  Caminhão-trator  IVECO/STRALIS 800S48TZ                    2022       Condutor  Lesões Graves     33  Masculino       0              0               1       0 -10.356019 -36.905522  SPRF-SE  DEL02-SE  UOP02-DEL02-SE
4  571838.0  1269159   2024-01-01  segunda-feira  05:00:00  MT  364  240        RONDONOPOLIS  Condutor deixou de manter distância do veículo da frente                Colisão traseira            Sem Vítimas    Pleno dia    Crescente              Céu Claro      Dupla          Reta      Não     1018348         Caminhão       SCANIA/P 310 B8X2                    2013       Condutor          Ileso     57  Masculino       1              0               0       0 -16.179141 -54.789053  SPRF-MT  DEL02-MT  UOP01-DEL02-MT

<class 'pandas.core.frame.DataFrame'>
Index: 455060 entries, 0 to 64124
Data columns (total 35 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      455060 non-null  float64
 1   pesid                   455060 non-null  int64
 2   data_inversa            455060 non-null  object
 3   dia_semana              455060 non-null  object
 4   horario                 455060 non-null  object
 5   uf                      455060 non-null  object
 6   br                      455060 non-null  int64
 7   km                      455060 non-null  object
 8   municipio               455060 non-null  object
 9   causa_acidente          455060 non-null  object
 10  tipo_acidente           455060 non-null  object
 11  classificacao_acidente  455045 non-null  object
 12  fase_dia                455060 non-null  object
 13  sentido_via             455060 non-null  object
 14  condicao_metereologica  455060 non-null  object
 15  tipo_pista              455060 non-null  object
 16  tracado_via             455060 non-null  object
 17  uso_solo                455060 non-null  object
 18  id_veiculo              455060 non-null  int64
 19  tipo_veiculo            440220 non-null  object
 20  marca                   455060 non-null  object
 21  ano_fabricacao_veiculo  455060 non-null  int64
 22  tipo_envolvido          415118 non-null  object
 23  estado_fisico           415118 non-null  object
 24  idade                   455060 non-null  int64
 25  sexo                    415118 non-null  object
 26  ilesos                  455060 non-null  int64
 27  feridos_leves           455060 non-null  int64
 28  feridos_graves          455060 non-null  int64
 29  mortos                  455060 non-null  int64
 30  latitude                455060 non-null  object
 31  longitude               455060 non-null  object
 32  regional                455037 non-null  object
 33  delegacia               454892 non-null  object
 34  uop                     454524 non-null  object
dtypes: float64(1), int64(9), object(25)
memory usage: 125.0+ MB

None

                  id         pesid            br    id_veiculo  ano_fabricacao_veiculo         idade        ilesos  feridos_leves  feridos_graves        mortos
count   64125.000000  6.412500e+04  64125.000000  6.412500e+04            64125.000000  64125.000000  64125.000000   64125.000000    64125.000000  64125.000000
mean   755962.790565  1.549108e+06    211.914183  1.311155e+06             1844.490292     33.385435      0.396476       0.329637        0.100101      0.029910
std      7549.119182  4.795325e+05    127.549257  2.309344e+05              560.458865     31.824495      0.489169       0.470085        0.300137      0.170341
min    742884.000000  0.000000e+00      0.000000  0.000000e+00                0.000000      0.000000      0.000000       0.000000        0.000000      0.000000
25%    749472.000000  1.676288e+06    101.000000  1.337786e+06             2008.000000     21.000000      0.000000       0.000000        0.000000      0.000000
50%    755924.000000  1.694434e+06    163.000000  1.350582e+06             2014.000000     34.000000      0.000000       0.000000        0.000000      0.000000
75%    762526.000000  1.712184e+06    324.000000  1.364199e+06             2021.000000     47.000000      1.000000       1.000000        0.000000      0.000000
max    772176.000000  1.737879e+06    495.000000  1.383658e+06             2026.000000   2025.000000      1.000000       1.000000        1.000000      1.000000

id                           0
pesid                        0
data_inversa                 0
dia_semana                   0
horario                      0
uf                           0
br                           0
km                           0
municipio                    0
causa_acidente               0
tipo_acidente                0
classificacao_acidente       5
fase_dia                     0
sentido_via                  0
condicao_metereologica       0
tipo_pista                   0
tracado_via                  0
uso_solo                     0
id_veiculo                   0
tipo_veiculo              1922
marca                        0
ano_fabricacao_veiculo       0
tipo_envolvido            5600
estado_fisico             5600
idade                        0
sexo                      5600
ilesos                       0
feridos_leves                0
feridos_graves               0
mortos                       0
latitude                     0
longitude                    0
regional                     6
delegacia                   17
uop                         31
dtype: int64

## Transformando a coluna ano veículo
Olhando para as informações do discribe() é possível observar que o valor mínimo é 0, ou seja veiculos sem a informação de ano, no lugar de 0 deveria existir null para não influenciar calculos de métricas posteriormente e saber da ausência de informação

In [11]:
dataset.loc[dataset["ano_fabricacao_veiculo"] == 0, "ano_fabricacao_veiculo"] = pd.NA